version: 0.2

env:
  variables:
    PROJECT_NAME: "etl-flight-data"
    PATH: "AWS/$PROJECT_NAME"
    BUCKET_NAME: "scripts-personal-projects"
    GLUE_JOB_CONFIG : "$PATH/glue_job_config.json"
    GLUE_JOB_NAME: "glue-job-$PROJECT_NAME"

phases:
  install:
    runtime-versions:
      python: 3.9 # Use the Python version compatible with AWS Glue
    commands:
      - python3 -m venv /root/venv
      - . /root/venv/bin/activate
      - echo "Installing required dependencies..."
      - pip install --upgrade pip
      - pip install boto3 awscli

  pre_build:
    commands:
      - echo "Uploading the script to S3..."
      - aws s3 cp --recursive $PATH s3://$BUCKET_NAME/aws_glue/$PROJECT_NAME

  build:
    commands:
      - echo "Checking if AWS Glue job exists..."
      - JOB_EXISTS=$(aws glue get-job --job-name $GLUE_JOB_NAME 2>/dev/null || echo "NOT_FOUND")
      - if [ "$JOB_EXISTS" == "NOT_FOUND" ]; then
          echo "Glue job not found. Creating a new job...";
          aws glue create-job --cli-input-json file://$GLUE_JOB_CONFIG;
        else
          echo "Glue job exists. Updating the job...";
          aws glue update-job --job-name $GLUE_JOB_NAME --job-update file://$GLUE_JOB_CONFIG;
        fi
