pipeline_ecommerce:
  outputs:
    dev:
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: ecommerce-demo-123
      dataset: ecommerce_raw
      threads: 3
      type: bigquery
  target: dev
